[package]
name = "deadmkt-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
bcs = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }

[features]
integration = []
